spring:
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: booking-service

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG