spring:
  config:
    import: optional:configserver:http://config-server:8888
    # import: optional:configserver:http://localhost:8888
  application:
    name: account-service

jwt:
  secret: ThisIsASecretKeyForBookingCareApplicationThatIsVeryLongAndSecure1234567890
  expiration: 86400000  # 1 ngày (24 * 60 * 60 * 1000 ms)
  refresh-token:
    expiration: 604800000 # 7 ngày

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

