spring:
  config:
    import: optional:configserver:http://config-server:8888
    # import: optional:configserver:http://localhost:8888

  application:
    name: expertise-service

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
